import { Option } from '@/components/Base/CustomInput.vue'

export const facultyOptions: Option[] = [
    {label: '医学部', value: '医学部'},
    {label: '冶金与能源工程学院', value: '冶金与能源工程学院'},
    {label: '生命科学与技术学院', value: '生命科学与技术学院'},
    {label: '环境科学与工程学院', value: '环境科学与工程学院'},
    {label: '材料科学与工程学院', value: '材料科学与工程学院'},
    {label: '国土资源工程学院', value: '国土资源工程学院'},
    {label: '机电工程学院', value: '机电工程学院'},        
    {label: '信息工程与自动化学院（人工智能产业学院）', value: '信息工程与自动化学院（人工智能产业学院）'},       
    {label: '建筑工程学院', value: '建筑工程学院'},        
    {label: '建筑与城市规划学院', value: '建筑与城市规划学院'},
    {label: '化学工程学院', value: '化学工程学院'},        
    {label: '交通工程学院', value: '交通工程学院'},        
    {label: '电力工程学院', value: '电力工程学院'},        
    {label: '民航与航空学院', value: '民航与航空学院'},    
    {label: '公共安全与应急管理学院', value: '公共安全与应急管理学院'},
    {label: '现代农业工程学院', value: '现代农业工程学院'},
    {label: '食品科学与工程学院', value: '食品科学与工程学院'},
    {label: '管理与经济学院', value: '管理与经济学院'},    
    {label: '理学院', value: '理学院'},
    {label: '基础医学院', value: '基础医学院'},
    {label: '法学院', value: '法学院'},
    {label: '艺术与传媒学院', value: '艺术与传媒学院'},    
    {label: '马克思主义学院', value: '马克思主义学院'},    
    {label: '外国语言文化学院', value: '外国语言文化学院'},
    {label: '城市学院', value: '城市学院'},
    {label: '国际学院', value: '国际学院'},
    {label: '体育学院', value: '体育学院'},
    {label: '继续教育学院', value: '继续教育学院'},        
    {label: '云南工业干部培训基地', value: '云南工业干部培训基地'},
    {label: '灵长类转化医学研究院', value: '灵长类转化医学研究院'}, 
]

export const gradeOptions: Option[] = [
    { label: '2010', value: '2010' },
    { label: '2011', value: '2011' },
    { label: '2012', value: '2012' },
    { label: '2013', value: '2013' },
    { label: '2014', value: '2014' },
    { label: '2015', value: '2015' },
    { label: '2016', value: '2016' },
    { label: '2017', value: '2017' },
    { label: '2018', value: '2018' },
    { label: '2019', value: '2019' },
    { label: '2020', value: '2020' },
    { label: '2021', value: '2021' },
    { label: '2022', value: '2022' },
    { label: '2023', value: '2023' },
    { label: '2024', value: '2024' },
    { label: '2025', value: '2025' },
]