spring.application.name=bookmanager

spring.jackson.time-zone=Asia/Shanghai

spring.datasource.url=jdbc:mysql://localhost:3306/bookmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=iqshe921hd90iwdbfg9832ud0n3498rjio3n4fjg4895fuer23urj8392fyrh8923h90dgh4987fh394fh2909u234fjh9042
jwt.expiration=86400000

spring.security.user.name=
spring.security.user.password=
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

time.offset=8
time.server-time-zone=Asia/Shanghai

system.max-borrow-count=5
system.default-borrow-days=30
system.penalty-per-day=0.5
